test:
  database: circle_ruby_test
  adapter: postgresql
  encoding: unicode
  pool: <%= (ENV["DB_POOL"] || ((ENV["RAILS_MAX_THREADS"] || 5 ).to_i + 1)).to_i %>
  timeout: 5000
  username: ubuntu
  host: localhost
